"""re-init_all

Revision ID: 1f4570af9832
Revises: 
Create Date: 2025-12-25 13:42:42.338743

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f4570af9832"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("account", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("account"),
    )
    op.create_table(
        "book",
        sa.Column(
            "book_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=False),
        sa.Column("publisher", sa.Text(), nullable=False),
        sa.Column("isbn", sa.String(length=17), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("series", sa.Text(), nullable=True),
        sa.Column("publish_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("book_id"),
        sa.UniqueConstraint("isbn"),
        sa.UniqueConstraint("isbn", name="uc_isbn"),
    )
    op.create_table(
        "bookstore",
        sa.Column(
            "bookstore_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("phone_number", sa.CHAR(length=10), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("shipping_fee", sa.Integer(), nullable=False),
        sa.CheckConstraint("shipping_fee >= 0", name="shipping_fee_non_negative"),
        sa.PrimaryKeyConstraint("bookstore_id"),
    )
    op.create_table(
        "customer",
        sa.Column("account", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.CHAR(length=10), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("account"),
    )
    op.create_table(
        "book_bookstore_mapping",
        sa.Column(
            "book_bookstore_mapping_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("store_quantity", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("bookstore_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("price >= 0", name="price_non_negative"),
        sa.CheckConstraint("store_quantity >= 0", name="store_quantity_non_negative"),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.book_id"],
        ),
        sa.ForeignKeyConstraint(
            ["bookstore_id"],
            ["bookstore.bookstore_id"],
        ),
        sa.PrimaryKeyConstraint("book_bookstore_mapping_id"),
    )
    op.create_table(
        "shopping_cart",
        sa.Column(
            "cart_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("customer_account", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_account"],
            ["customer.account"],
        ),
        sa.PrimaryKeyConstraint("cart_id"),
    )
    op.create_table(
        "staff",
        sa.Column("account", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("bookstore_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bookstore_id"],
            ["bookstore.bookstore_id"],
        ),
        sa.PrimaryKeyConstraint("account"),
    )
    op.create_table(
        "cart_item",
        sa.Column(
            "cart_item_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Uuid(), nullable=False),
        sa.Column("book_bookstore_mapping_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity >= 0", name="quantity_non_negative"),
        sa.ForeignKeyConstraint(
            ["book_bookstore_mapping_id"],
            ["book_bookstore_mapping.book_bookstore_mapping_id"],
        ),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["shopping_cart.cart_id"],
        ),
        sa.PrimaryKeyConstraint("cart_item_id"),
    )
    op.create_table(
        "coupon",
        sa.Column(
            "coupon_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("discount_percentage", sa.Numeric(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("admin_account", sa.Text(), nullable=True),
        sa.Column("staff_account", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "discount_percentage >= 0 AND discount_percentage <= 1",
            name="discount_percentage_check",
        ),
        sa.ForeignKeyConstraint(
            ["admin_account"],
            ["admin.account"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_account"],
            ["staff.account"],
        ),
        sa.PrimaryKeyConstraint("coupon_id"),
    )
    op.create_table(
        "order_",
        sa.Column(
            "order_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("order_time", sa.Date(), nullable=False),
        sa.Column("customer_name", sa.Text(), nullable=False),
        sa.Column("customer_phone_number", sa.CHAR(length=10), nullable=False),
        sa.Column("customer_email", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("total_price", sa.Integer(), nullable=False),
        sa.Column("shipping_address", sa.Text(), nullable=False),
        sa.Column("shipping_fee", sa.Integer(), nullable=False),
        sa.Column("recipient_name", sa.Text(), nullable=False),
        sa.Column("coupon_id", sa.Uuid(), nullable=True),
        sa.Column("customer_account", sa.Text(), nullable=False),
        sa.CheckConstraint("shipping_fee >= 0", name="shipping_fee_non_negative"),
        sa.CheckConstraint("total_price >= 0", name="total_price_non_negative"),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupon.coupon_id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_account"],
            ["customer.account"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "order_item",
        sa.Column(
            "order_item_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("book_bookstore_mapping_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("price >= 0", name="price_non_negative"),
        sa.CheckConstraint("quantity >= 0", name="quantity_non_negative"),
        sa.ForeignKeyConstraint(
            ["book_bookstore_mapping_id"],
            ["book_bookstore_mapping.book_bookstore_mapping_id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order_.order_id"],
        ),
        sa.PrimaryKeyConstraint("order_item_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_item")
    op.drop_table("order_")
    op.drop_table("coupon")
    op.drop_table("cart_item")
    op.drop_table("staff")
    op.drop_table("shopping_cart")
    op.drop_table("book_bookstore_mapping")
    op.drop_table("customer")
    op.drop_table("bookstore")
    op.drop_table("book")
    op.drop_table("admin")
    # ### end Alembic commands ###
