"""order_item_price_required

Revision ID: 48034a472c9b
Revises: afda2edf0ad8
Create Date: 2025-12-24 13:30:33.928209

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48034a472c9b"
down_revision = "afda2edf0ad8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order_item", "price", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order_item", "price", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
