"""staff_bookstoreid_nullable

Revision ID: 555243a9ed22
Revises: 0a1e1db058ba
Create Date: 2025-11-26 16:59:53.792494

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "555243a9ed22"
down_revision = "0a1e1db058ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("staff", "bookstore_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("staff", "bookstore_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
