"""add_coupon_name

Revision ID: 5e3f2ead77f0
Revises: 188a0a224d99
Create Date: 2025-12-09 13:12:40.825792

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e3f2ead77f0"
down_revision = "188a0a224d99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookstore", "verified")
    op.add_column("coupon", sa.Column("name", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coupon", "name")
    op.add_column(
        "bookstore", sa.Column("verified", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
