"""add_uc_on_book_isbn

Revision ID: afda2edf0ad8
Revises: 5e3f2ead77f0
Create Date: 2025-12-17 11:27:04.720286

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "afda2edf0ad8"
down_revision = "5e3f2ead77f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uc_isbn", "book", ["isbn"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uc_isbn", "book", type_="unique")
    # ### end Alembic commands ###
