"""add_bookstore_verified

Revision ID: 188a0a224d99
Revises: 555243a9ed22
Create Date: 2025-12-08 13:35:31.208847

"""

from alembic import op
import sqlalchemy as sa
from app.db.models.coupon import Coupon
from app.enum.coupon import CouponType


# revision identifiers, used by Alembic.
revision = "188a0a224d99"
down_revision = "555243a9ed22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookstore", sa.Column("verified", sa.Boolean()))

    coupon_types = [type_enum.value for type_enum in list(CouponType)]

    query = (
        sa.update(Coupon)
        .where(Coupon.type.not_in(coupon_types))
        .values(type=CouponType.SPECIAL_EVENT)
    )

    connection = op.get_bind()

    connection.execute(query)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookstore", "verified")
    # ### end Alembic commands ###
