"""add_bookstore_verified

Revision ID: 188a0a224d99
Revises: 555243a9ed22
Create Date: 2025-12-08 13:35:31.208847

"""

from alembic import op
import sqlalchemy as sa
from app.db.models.bookstore import Bookstore


# revision identifiers, used by Alembic.
revision = "188a0a224d99"
down_revision = "555243a9ed22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookstore", sa.Column("verified", sa.Boolean()))

    query = sa.update(Bookstore).where(Bookstore.verified.is_(None)).values(verified=True)

    connection = op.get_bind()

    connection.execute(query)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookstore", "verified")
    # ### end Alembic commands ###
