import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import TypeDecorator, engine_from_config, pool
from sqlalchemy.ext.asyncio import AsyncEngine


# to import all models
import app.db.models as m  # noqa
from app.core.config import settings
from app.db.models.base import Base

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config
config.set_main_option("sqlalchemy.url", settings.DATABASE_URI)
# Interpret the config file for Python logging.
# This line sets up loggers basically.
fileConfig(config.config_file_name)  # type: ignore

# add your model's MetaData object here
# for 'autogenerate' support
# from myapp import mymodel
# target_metadata = mymodel.Base.metadata
target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline():
    """Run migrations in 'offline' mode.
    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.
    Calls to context.execute() here emit the given string to the
    script output.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def render_item(type_, obj, autogen_context):
    """Apply custom rendering for selected items."""

    if type_ == "type" and isinstance(obj, TypeDecorator):
        if obj.impl.__class__.__name__ == "JSONB":  # type: ignore
            autogen_context.imports.add("from sqlalchemy.dialects import postgresql")
            return "postgresql.JSONB(astext_type=sa.Text())"
        return f"sa.{obj.impl!r}"

    # default rendering for other objects
    return False


def do_run_migrations(connection):
    def _process_revision_directives(context, revision, directives):
        """
        This function can prevent the empty revision file generated by:
        alembic revision


        """
        if config.cmd_opts.autogenerate:  # type: ignore
            script = directives[0]
            if script.upgrade_ops.is_empty():
                directives[:] = []
                print("No changes in schema detected.")

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        process_revision_directives=_process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online():
    """Run migrations in 'online' mode.
    In this scenario we need to create an Engine
    and associate a connection with the context.
    """
    connectable = AsyncEngine(
        engine_from_config(
            config.get_section(config.config_ini_section),  # type: ignore
            prefix="sqlalchemy.",
            poolclass=pool.NullPool,
            future=True,
        )
    )

    async with connectable.connect() as connection:
        context.configure(
            connection=connection,  # type: ignore
            target_metadata=target_metadata,
            render_item=render_item,
        )
        await connection.run_sync(do_run_migrations)


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
    pass

if __name__ == "__main__":
    asyncio.run(run_migrations_online())
